"""
ISO 639-1/639-2 language codes mapping.
Reference: https://iso639-3.sil.org/code_tables/639/data
"""

from typing import Dict

LANGUAGE_CODES: Dict[str, str] = {
    "Afrikaans": "afr",
    "Amharic": "amh",
    "Arabic": "ara",
    "Aragonese": "arg",
    "Assamese": "asm",
    "Azerbaijani": "aze",
    "Bengali": "ben",
    "Bosnian": "bos",
    "Bulgarian": "bul",
    "Catalan": "cat",
    "Czech": "ces",
    "Mandarin": "cmn",
    "Welsh": "cym",
    "Danish": "dan",
    "German": "deu",
    "Greek": "ell",
    "English": "eng",
    "Esperanto": "epo",
    "Estonian": "est",
    "Basque": "eus",
    "Farsi": "fas",
    "Finnish": "fin",
    "French": "fra",
    "Galician": "glg",
    "Ancient Greek": "grc",
    "Guarani": "grn",
    "Gujarati": "guj",
    "Hebrew": "heb",
    "Hindi": "hin",
    "Croatian": "hrv",
    "Hungarian": "hun",
    "Armenian": "hye",
    "Indonesian": "ind",
    "Icelandic": "isl",
    "Italian": "ita",
    "Lojban": "jbo",
    "Japanese": "jpn",
    "Kalaallisut": "kal",
    "Kannada": "kan",
    "Georgian": "kat",
    "Kirghiz": "kir",
    "Korean": "kor",
    "Kurdish": "kur",
    "Latin": "lat",
    "Latvian": "lav",
    "Lingua Franca Nova": "lfn",
    "Lithuanian": "lit",
    "Malayalam": "mal",
    "Marathi": "mar",
    "Macedonian": "mkd",
    "Maltese": "mlt",
    "Malay": "msa",
    "Burmese": "mya",
    "Nahuatl": "nah",
    "Nepali": "nep",
    "Dutch": "nld",
    "Norwegian": "nor",
    "Oriya": "ori",
    "Oromo": "orm",
    "Punjabi": "pan",
    "Papiamento": "pap",
    "Polish": "pol",
    "Portuguese": "por",
    "Romanian": "ron",
    "Russian": "rus",
    "Sinhala": "sin",
    "Slovak": "slk",
    "Slovenian": "slv",
    "Spanish": "spa",
    "Albanian": "sqi",
    "Serbian": "srp",
    "Swahili": "swa",
    "Swedish": "swe",
    "Tamil": "tam",
    "Tatar": "tat",
    "Telugu": "tel",
    "Thai": "tha",
    "Tswana": "tsn",
    "Turkish": "tur",
    "Ukrainian": "ukr",
    "Urdu": "urd",
    "Vietnamese": "vie",
    "Cantonese": "yue",
    "Chinese": "zho"
}